### ISSUE TITLE
How DC point can be added to S-parm dataset to allow impulse & step simulations

### ISSUE THREAD

**Issue by kschmahl** [TeledyneLeCroy/SignalIntegrity#59]
Pete,
Quite a while ago I asked why my S-parameter dataset was not producing time domain impulse & step response waveforms when I load the file.  You rightly said that its because there is no DC point in the S-parameter dataset.
You then proceeded to describe how the tool can be made to generate that DC point by interpolation from the existing data.  But, sadly, I lost that email thread and it's not discussed in this forum.
I also note you have improved (fixed) that DC point subject in errata for the book, so maybe it improves the code's calculations since last we talked.

Could you speak to that again for everyone's benefit?
Thanks!

**Comment by eceforge** [comment]
I found that you can force the S-parameter viewer to re-sample the data by going to the s-parameter properties in the viewer and changing ... something. Really anything. the number of points is usually the best target that makes sense to me, but even changing the reference impedance to the same value triggers a re-sampling. once you hit enter and close the properties window, you should now see the impulse and step response simulations based on the newly resampled, evenly spaced frequency steps. 

This also had me super confused for a while as to why files that I imported from a simulation didn't show the impulse and step responses despite having a 0.0Hz entry in the touchstone file. Turns out the documentation does actually allude to this issue a bit [S-Parameter Viewer Docs](http://teledynelecroy.github.io/SignalIntegrity/SignalIntegrity/App/Help/Help.html.LyXconv/Help-Section-13.html#toc-Section-13). Saying that it needs **both** a DC data point and evenly spaced frequencies.

**Comment by kschmahl** [comment]
Ah, excellent, thanks.  
Yes, I did see his comment on needing both DC point and evenly spaced.
I can fix that by dropping an S-param model on the sheet, hooking up Ports, defining the sweep and resampling.

Thank you for replying to my old post.  Glad to see a reply!
