### ISSUE TITLE
Offset in "View s-parameters according to calc properties" data in the CTLE properties menu

### ISSUE THREAD

**Issue by 6Sim9** [TeledyneLeCroy/SignalIntegrity#61]
Maybe I'm wrong but I think there's an issue with the "View s-parameters according to calc properties" data in the CTLE properties menu.
The S21 seems to be offset by +6dB on the plot. 
I ploted the H(f) equation described in HELP menu. The result is 6dB below the S21 plot in SignalIntegrity.
The signal passing through the CTLE to an eye diagram seems correctly computed.

**Comment by PetePupalaikis** [comment]
This is not actually a bug.  Since the s-parameter component is modeled as an infinite, high impedance input and a zero impedance output, with the CTLE transfer function in between, when you plot the s-parameters, it has a 6 dB offset.  If you placed the CTLE in a simulation and ran it and looked at the transfer function, this +6 dB offset disappears.

**Comment by kschmahl** [comment]
Pete, I'm gonna have to cogitate on this for a while.
Is there a cogent section of your book that can help me see this better?
Maybe not directly related, but is mathematically relevant?
thanks
ken

**Comment by PetePupalaikis** [comment]
Hi Ken:

Yes -- take a look at page 585 onward.  You will see exactly this topic being discussed.

Pete

**Comment by PetePupalaikis** [comment]
And again, you can see on page 164 where I show the s-parameters of a two-port voltage amplifier (which the CTLE is, sort of), that the S21 = twice the gain (hence the 6 dB).

Pete
